name: CI

on:
  push:
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  nodejs:
    name: Node.js
    runs-on: ubuntu-latest
    concurrency: ci-nodejs-${{ github.ref }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install Packages
        run: pnpm install

      # - name: Build Server
      #   run: pnpm run build
      #   working-directory: ./server

      - name: Build Client
        working-directory: ./client
        run: pnpm exec vite build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: './client/dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
  lint:
    name: Lint
    runs-on: ubuntu-latest
    concurrency: ci-lint-${{ github.ref }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      - name: Run Biome
        run: biome ci .
